server:
  port: 8080
spring:
  application:
    name: user
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 6000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lixc
    url: jdbc:mysql://localhost:3306/sw?useUnicode=true&characterEncoding=UTF-8&useSSL=false&nullNamePatternMatchesAll=true&autoReconnect=true&serverTimezone=GMT%2B8
  mail:
    host: smtp.163.com #发送邮件服务器
    username: lixianchun2016x@163.com #发送邮件的邮箱地址
    password: WWFMZSBCAKTIEIES #客户端授权码，不是邮箱密码
    from: lixianchun2016x@163.com # 发送邮件的地址，和上面username一致
    default-encoding: utf-8
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 3MB

#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.example.lixc.enums.BaseEnumTypeHandler
  mapper-locations: classpath*:mybatis/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.lixc.entity  # 注意：重点这是对应实体类的路径

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql #分页数据源
  reasonable: true #是否开启分页limit 默认不开启
  #  rowBoundsWithCount: true
  supportMethodsArguments: false #是否从多方数据源获取分页，有一个坑，当前端传入页数超过查询总页数，开启式会默认当前前端总页数为查询总页数到时发生异常，不建议开启
  params: count=countSql #supportMethodsArguments 开启式手动配置的分页参数

logging:
  config: classpath:log4j2-spring.xml
  level:
    #    root: INFO
    cn.jay.repository: trace

sw:
  code:
    length: 9
  redis:
    expireTime: 10000
  mail:
    subject: 慢蜗社区注册认证邮件
    content: <html> <p class="text-center"> 验证地址：<a href="{content}">{content1}</a></p></body> </html>
    content1: 邮箱已验证成功，点击<a href="{}">登录</a>进入慢蜗社区。

  work:
    url: E:\\Users\\11930\\Desktop\\upload\\
    headImageUrl: E:\\Users\\11930\\Desktop\\headImage\\
    thumbRatio: 0.2